# Generated by Django 6.0.6 on 2026-06-10 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('pickup_address', models.CharField(max_length=500)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('dropoff_address', models.CharField(max_length=500)),
                ('distance_km', models.FloatField(default=0)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('fare_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vehicle_type', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('premium', 'Premium')], default='economy', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('arriving', 'Driver Arriving'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=15)),
                ('payment_method', models.CharField(choices=[('jazzcash', 'JazzCash'), ('wallet', 'Wallet'), ('cash', 'Cash')], default='cash', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_as_driver', to='accounts.driverprofile')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_passenger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rides',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='rides_status_376a74_idx'), models.Index(fields=['passenger', '-requested_at'], name='rides_passeng_8e4af4_idx'), models.Index(fields=['driver', '-requested_at'], name='rides_driver__502ed8_idx')],
            },
        ),
    ]
